security:
    password_hashers:
        App\Entity\User:
            algorithm: bcrypt

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\ApiTokenAuthenticator
            stateless: true

    access_control:
        - { path: ^/users$, roles: PUBLIC_ACCESS, methods: [POST] }
        - { path: ^/auth/login$, roles: PUBLIC_ACCESS }
        - { path: ^/, roles: ROLE_USER }
